### ISSUE TITLE
test13.html

### ISSUE THREAD

**Issue by aciddust** [yunsangil/javascript#2]
function ShowMsg(textData){
    document.getElementById("calenderresult").innerHTML=textData+"일 입니다.";
}
function calender(A,B){
    A/=1;
    B/=1;
    var day=0;
    document.getElementById("year").innerHTML=A+"년"+B+"월의 일수는"

    switch(B){
            case 1:
            case 3:
            case 5:
            case 7:
            case 8:
            case 10:
                ShowMsg(31);
                break;
            case 2:
                if(A%4==0){
                    ShowMsg(29);
                }
                else{
                    ShowMsg(28);
                }
                break;
            case 4:
            case 6:
            case 9:
            case 11:
                ShowMsg(30);
                break;
            default:
                document.getElementById("calenderresult").innerHTML="현재 입력된 값이 1~12의 범위에 있지 않기 때문에 출력이 안됩니다.";
                break;
    }
    
}

**Comment by yunsangil** [comment]
thx
